siteTitle = "Blog by John Doe"
siteDescr = "Rising front-end developer"
siteAuthor = "Tomasz Trzaskoma"


siteGithubUrl = "http://github.com/przytrzask"
siteEmailUrl = "trzaskoma86@gmail.com"
linkedinUrl = "http://linkedin.com/in/tomasz-trzaskoma-a37557b5/"



googleAnalyticsId = "trzasq"

linkPrefix = "./"